config/routes.rb
require 'sidekiq/web'

GitlabCi::Application.routes.draw do
  # API
  API::API.logger Rails.logger
  mount API::API => '/api'

  resource :help

  resources :projects do
    collection do
      post :add
      get :gitlab
    end

    member do
      get :status, to: 'projects#badge'
      get :integration
      post :build
    end

    resource :charts, only: [:show]

    resources :builds, only: [:show] do
      member do
        get :cancel
        get :status
        post :retry
      end
    end

    resources :web_hooks, only: [:index, :create, :destroy] do
      member do
        get :test
      end
    end
  end

  resource :user_sessions

  namespace :admin do
    resources :runners, only: [:index, :show, :update, :destroy] do
      member do
        put :assign_all
      end
    end

    resources :projects do
      resources :runner_projects
    end
  end

  root :to => 'projects#index'
end

app/models/web_hook.rb
# == Schema Information
#
# Table name: web_hooks
#
#  id         :integer          not null, primary key
#  url        :string(255)      not null
#  project_id :integer          not null
#  created_at :datetime
#  updated_at :datetime
#

class WebHook < ActiveRecord::Base
  include HTTParty

  belongs_to :project

  attr_accessible :url

  # HTTParty timeout
  default_timeout 10

  validates :url, presence: true,
                  format: { with: URI::regexp(%w(http https)), message: "should be a valid url" }

  def execute(data)
    parsed_url = URI.parse(url)
    if parsed_url.userinfo.blank?
      WebHook.post(url, body: data.to_json, headers: { "Content-Type" => "application/json" }, verify: false)
    else
      post_url = url.gsub("#{parsed_url.userinfo}@", "")
      auth = {
        username: URI.decode(parsed_url.user),
        password: URI.decode(parsed_url.password),
      }
      WebHook.post(post_url,
                   body: data.to_json,
                   headers: {"Content-Type" => "application/json"},
                   verify: false,
                   basic_auth: auth)
    end
  end
end

app/controllers/web_hooks_controller.rb
class WebHooksController < ApplicationController
  before_filter :authenticate_user!
  before_filter :project
  before_filter :authorize_access_project!

  layout 'project'

  def index
    @web_hooks = @project.web_hooks
    @web_hook = WebHook.new
  end

  def create
    @web_hook = @project.web_hooks.new(params[:web_hook])
    @web_hook.save

    if @web_hook.valid?
      redirect_to project_web_hooks_path(@project)
    else
      @web_hooks = @project.web_hooks.select(&:persisted?)
      render :index
    end
  end

  def test
    TestHookService.new.execute(hook, current_user)

    redirect_to :back
  end

  def destroy
    hook.destroy

    redirect_to project_web_hooks_path(@project)
  end

  private

  def hook
    @web_hook ||= @project.web_hooks.find(params[:id])
  end

  def project
    @project = Project.find(params[:project_id])
  end
end

app/views/web_hooks/index.html.haml
%h3
  Web hooks

%p.light
  Web Hooks can be used for binding events when build completed.

%hr.clearfix

= form_for [@project, @web_hook], html: { class: 'form-horizontal' } do |f|
  -if @web_hook.errors.any?
    .alert.alert-danger
      - @web_hook.errors.full_messages.each do |msg|
        %p= msg
  .form-group
    = f.label :url, "URL", class: 'control-label'
    .col-sm-10
      = f.text_field :url, class: "form-control", placeholder: 'http://example.com/trigger-ci.json'
  .form-actions
    = f.submit "Add Web Hook", class: "btn btn-create"

-if @web_hooks.any?
  %h4 Activated web hooks (#{@web_hooks.count})
  %table.table
    - @web_hooks.each do |hook|
      %tr
        %td
          .clearfix
            %span.monospace= hook.url
        %td
          .pull-right
            = link_to 'Test Hook', test_project_web_hook_path(@project, hook), class: "btn btn-small btn-grouped"
            = link_to 'Remove', project_web_hook_path(@project, hook), data: { confirm: 'Are you sure?'}, method: :delete, class: "btn btn-remove btn-small btn-grouped"

%h4 Web Hook data example

:erb
  <pre>
    <code>
      {
        "build_id": 2,
        "build_status": "failed",
        "build_started_at": "2014-05-05T18:01:02.563Z",
        "build_finished_at": "2014-05-05T18:01:07.611Z",
        "project_id": 1,
        "project_name": "Brightbox \/ Brightbox Cli",
        "gitlab_url": "http:\/\/localhost:3000\/brightbox\/brightbox-cli",
        "ref": "master",
        "sha": "a26cf5de9ed9827746d4970872376b10d9325f40",
        "before_sha": "34f57f6ba3ed0c21c5e361bbb041c3591411176c",
        "push_data": {
          "before": "34f57f6ba3ed0c21c5e361bbb041c3591411176c",
          "after": "a26cf5de9ed9827746d4970872376b10d9325f40",
          "ref": "refs\/heads\/master",
          "user_id": 1,
          "user_name": "Administrator",
          "project_id": 5,
          "repository": {
            "name": "Brightbox Cli",
            "url": "dzaporozhets@localhost:brightbox\/brightbox-cli.git",
            "description": "Voluptatibus quae error consectetur voluptas dolores vel excepturi possimus.",
            "homepage": "http:\/\/localhost:3000\/brightbox\/brightbox-cli"
          },
          "commits": [
            {
              "id": "a26cf5de9ed9827746d4970872376b10d9325f40",
              "message": "Release v1.2.2",
              "timestamp": "2014-04-22T16:46:42+03:00",
              "url": "http:\/\/localhost:3000\/brightbox\/brightbox-cli\/commit\/a26cf5de9ed9827746d4970872376b10d9325f40",
              "author": {
                "name": "Paul Thornthwaite",
                "email": "tokengeek@gmail.com"
              }
            },
            {
              "id": "34f57f6ba3ed0c21c5e361bbb041c3591411176c",
              "message": "Fix server user data update\n\nIncorrect condition was being used so Base64 encoding option was having\nopposite effect from desired.",
              "timestamp": "2014-04-11T18:17:26+03:00",
              "url": "http:\/\/localhost:3000\/brightbox\/brightbox-cli\/commit\/34f57f6ba3ed0c21c5e361bbb041c3591411176c",
              "author": {
                "name": "Paul Thornthwaite",
                "email": "tokengeek@gmail.com"
              }
            }
          ],
          "total_commits_count": 2,
        }
      }
    </code>
  </pre>