config/routes.rb
require 'sidekiq/web'

GitlabCi::Application.routes.draw do
  # API
  API::API.logger Rails.logger
  mount API::API => '/api'

  resource :help

  resources :projects do
    collection do
      post :add
      get :gitlab
    end

    member do
      get :status, to: 'projects#badge'
      get :integration
      post :build
    end

    resource :charts, only: [:show]

    resources :builds, only: [:show] do
      member do
        get :cancel
        get :status
        post :retry
      end
    end

    resources :web_hooks, only: [:index, :create, :destroy] do
      member do
        get :test
      end
    end
  end

  resource :user_sessions

  namespace :admin do
    resources :runners, only: [:index, :show, :update, :destroy] do
      member do
        put :assign_all
      end
    end

    resources :projects do
      resources :runner_projects
    end
  end

  root :to => 'projects#index'
end

app/models/runner.rb
# == Schema Information
#
# Table name: runners
#
#  id          :integer          not null, primary key
#  token       :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#  description :string(255)
#

class Runner < ActiveRecord::Base
  has_many :builds
  has_many :runner_projects, dependent: :destroy
  has_many :projects, through: :runner_projects

  has_one :last_build, ->() { order('id DESC') }, class_name: 'Build'

  attr_accessible :token, :description

  before_validation :set_default_values

  def set_default_values
    self.token = SecureRandom.hex(15) if self.token.blank?
  end

  def assign_to(project, current_user)
    project.runner_projects.create!(runner_id: self.id)
  end

  def display_name
    return token unless !description.blank?

    description
  end

  def shared?
    runner_projects.blank?
  end
end

app/controllers/admin/runners_controller.rb
class Admin::RunnersController < Admin::ApplicationController
  before_filter :authenticate_user!
  before_filter :runner, except: :index

  def index
    @runners = Runner.page(params[:page]).per(30)
  end

  def show
    @builds = @runner.builds.order('id DESC').first(30)
    @projects = Project.all
    @projects = @projects.where("projects.id NOT IN (?)", @runner.projects.pluck(:id)) if @runner.projects.any?
    @projects = @projects.page(params[:page]).per(30)
  end

  def update
    @runner.update_attributes(description: params[:runner][:description])

    respond_to do |format|
      format.js
      format.html { redirect_to admin_runners_path }
    end
  end

  def destroy
    @runner.destroy

    redirect_to admin_runners_path
  end

  def assign_all
    Project.unassigned(@runner).all.each { |project| @runner.assign_to(project, current_user) }

    respond_to do |format|
      format.js
      format.html { redirect_to admin_runners_path, notice: "Runner was assigned to all projects" }
    end
  end

  private

  def runner
    @runner ||= Runner.find(params[:id])
  end
end

app/views/admin/runners/_runner.html.haml
%tr{id: dom_id(runner)}
  %td
    = runner.id
  %td
    - if runner.shared?
      %span.label.label-success shared
    - else
      %span.label.label-info specific

  %td
    = link_to admin_runner_path(runner) do
      = runner.token
  %td
    .runner-description
      = runner.description
      %span (#{link_to 'edit', '#', class: 'edit-runner-link'})
    .runner-description-form.hide
      = form_for [:admin, runner], remote: true, html: { class: 'form-inline' } do |f|
        .form-group
          = f.text_field :description, class: 'form-control'
        = f.submit 'Save', class: 'btn'
        %span (#{link_to 'cancel', '#', class: 'cancel'})
  %td
    - if runner.shared?
      \-
    - else
      = runner.projects.count
  %td
    %span.label.label-success
      #{runner.builds.success.count}
    %span /
    %span.label.label-danger
      #{runner.builds.failed.count}
  %td
    #{time_ago_in_words(runner.created_at)} ago
  %td
    .pull-right
      = link_to 'Assign to all', assign_all_admin_runner_path(runner), class: 'btn btn-small assign-all-runner', title: 'Assign runner to all projects', method: :put, remote: true
      = link_to 'Remove', [:admin, runner], data: { confirm: "Are you sure?" }, method: :delete, class: 'btn btn-danger btn-small'

app/views/admin/runners/assign_all.js.haml
:plain
  $("#runner_#{@runner.id}").replaceWith("#{escape_javascript(render(@runner))}")

app/views/admin/runners/index.html.haml
= content_for :title do
  %h3.project-title
    Manage Runners

    .pull-right
      %small
        = pluralize(@runners.total_count, 'runner')

%p.lead
  %span To register new runner you should the following registration token. With this token the runner will request a unique runner token and use that for future communication.
  %code #{GitlabCi::REGISTRATION_TOKEN}

.bs-callout
  %p
    A 'runner' is a process which runs a build.
    You can setup as many runners as you need.
    %br
    Runners can be placed on separate users, servers, and even on your local machine.
    %br

  %div
    %span Each runner can be in one of the following states:
    %ul
      %li
        %span.label.label-success shared
        \- run any builds
      %li
        %span.label.label-info specific
        \- run only builds from assigned projects



%table.table
  %thead
    %tr
      %th ID
      %th Type
      %th Runner token
      %th Description
      %th Projects
      %th Builds Stats
      %th Registered
      %th

  = render @runners
= paginate @runners

app/views/admin/runners/show.html.haml
%h4.page-title
  Runner: #{@runner.token}

%p.light= @runner.description
%p
  = link_to admin_runners_path do
    &larr; Back to runners list
%hr

- if @runner.shared?
  .bs-callout.bs-callout-success
    %h4 This runner will process build from ALL projects
    %p If you want runner to build only specific projects you just need to enable them in table below
- else
  .bs-callout.bs-callout-info
    %h4 This runner will process build only from ASSIGNED projects
    %p If you want runner to build all projects you just need to disable all assignee projects
.row
  .col-md-6
    %h4 Restrict projects for this runner
    - if @runner.projects.any?
      %table.table
        %thead
          %tr
            %th Assigned projects
            %th
        - @runner.runner_projects.each do |runner_project|
          - project = runner_project.project
          %tr.alert-info
            %td
              %strong
                = project.name
            %td
              .pull-right
                = link_to 'Disable', [:admin, project, runner_project], method: :delete, class: 'btn btn-danger btn-xs'

    %table.table
      %thead
        %tr
          %th Project
          %th
      - @projects.each do |project|
        %tr
          %td
            = project.name
          %td
            .pull-right
              = form_for [:admin, project, project.runner_projects.new] do |f|
                = f.hidden_field :runner_id, value: @runner.id
                = f.submit 'Enable', class: 'btn btn-xs'
    = paginate @projects

  .col-md-6
    %h4 Recent builds served by this runner
    %table.builds.runner-builds
      %thead
        %tr
          %th Status
          %th Project
          %th Commit
          %th Finished at

      - @builds.each do |build|
        %tr.build.alert{class: build_status_alert_class(build)}
          %td.status
            = build.status

          %td.status
            = build.project.name

          %td.build-link
            = link_to project_build_path(build.project, build) do
              %strong #{build.short_sha}

          %td.timestamp
            - if build.finished_at
              %span #{time_ago_in_words build.finished_at} ago

app/views/admin/runners/update.js.haml
:plain
  $("#runner_#{@runner.id}").replaceWith("#{escape_javascript(render(@runner))}")