config/routes.rb
require 'sidekiq/web'

GitlabCi::Application.routes.draw do
  # API
  API::API.logger Rails.logger
  mount API::API => '/api'

  resource :help

  resources :projects do
    collection do
      post :add
      get :gitlab
    end

    member do
      get :status, to: 'projects#badge'
      get :integration
      post :build
    end

    resource :charts, only: [:show]

    resources :builds, only: [:show] do
      member do
        get :cancel
        get :status
        post :retry
      end
    end

    resources :web_hooks, only: [:index, :create, :destroy] do
      member do
        get :test
      end
    end
  end

  resource :user_sessions

  namespace :admin do
    resources :runners, only: [:index, :show, :update, :destroy] do
      member do
        put :assign_all
      end
    end

    resources :projects do
      resources :runner_projects
    end
  end

  root :to => 'projects#index'
end

app/views/notify/build_fail_email.html.haml
%p
  Build failed for
  = link_to project_url(@project) do
    = @project.name

%p
  Status: #{@build.status}
%p
  Commit: #{@build.short_sha}
%p
  Author: #{@build.git_author_name}

%p
  Url: #{link_to @build.short_sha, project_build_url(@build.project, @build)}

app/views/notify/build_fail_email.text.erb
Build failed for <%= @project.name %>

Status:   <%= @build.status %>
Commit:   <%= @build.short_sha %>
Author:   <%= @build.git_author_name %>

Url:      <%= project_build_url(@build.project, @build) %>

app/views/notify/build_success_email.html.haml
%p
  Build successful for
  = link_to project_url(@project) do
    = @project.name

%p
  Status: #{@build.status}
%p
  Commit: #{@build.short_sha}
%p
  Author: #{@build.git_author_name}

%p
  Url: #{link_to @build.short_sha, project_build_url(@build.project, @build)}

app/views/notify/build_success_email.text.erb
Build successful for <%= @project.name %>

Status:   <%= @build.status %>
Commit:   <%= @build.short_sha %>
Author:   <%= @build.git_author_name %>

Url:      <%= project_build_url(@build.project, @build) %>